#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

main() {
  local app="$1"
  local rev="$4"
  slack_notify "${app}" "${rev}"
}

slack_notify() {
  local app="$1"
  local rev="$2"
  local file="${DOKKU_ROOT}/${app}/SLACK_WEBHOOK"

  if [[ ! -s "${file}" ]]; then
    return 0
  fi

  local webhook="$(cat "${file}")"
  local payload="$(slack_payload "${app}" "${rev}")"

  dokku_log_info1 "Notifying Slack ..."
  curl \
    --request "POST" \
    --silent \
    --fail \
    --show-error \
    --location \
    --output "/dev/null" \
    --header "Content-Type: application/json" \
    --data "${payload}" \
    "${webhook}"
}

slack_payload() {
  local url=$(dokku url $1)
  local app="$1"
  local rev="$2"
  local hostname=$(hostname)

  cat <<JSON
{
  "attachments": [{
    "footer": "rev: ${rev}",
    "text": "Deploying **${app}** via ${url}",
    "fallback": "Deploying **${app}** via ${url}",
    "color": "#95A3B6",
    "mrkdwn_in": ["text"]
  }]
}
JSON
}

main $@
